apiVersion: v1
kind: Service
metadata:
  name: fsm
  labels:
    app: fsm
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3020
  selector:
    app: fsm
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fsm
  labels:
    app: fsm
spec:
  selector:
    matchLabels:
      app: fsm
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: fsm
      annotations:
        date: {{ now }} # RollingRestart workaround. https://github.com/kubernetes/kubernetes/issues/13488
    spec:
      containers:
      - name: fsm
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: Always
        env:
          - name: BASE_URL
            value: {{ .Values.ingress.path }}
        ports:
        - containerPort: 3020
          name: app
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "300m"
        # readinessProbe:
        #   httpGet:
        #     path: {{ .Values.ingress.path }}
        #     port: 3020
          periodSeconds: 3
          timeoutSeconds: 240
      imagePullSecrets:
        - name: {{.Values.dockerSecret}}
